name: Generate Json
#on:
#  schedule:
#  - cron: "0 22 * * *"
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - run: ruby main.rb > dnaustria.json
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO]"
          commit_message: "json update from remote"
